services:
  - type: web
    name: portfolio-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: EMAIL_USER
        value: jafferali.0741@gmail.com
      - key: EMAIL_PASS
        value: iwgm ylpo wpfn jkbq